apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: An example of a Backstage application.
  annotations:
    github.com/project-slug: DinuRajDeva/sample-python
spec:
  type: service
  owner: guests
  lifecycle: experimental
